### ISSUE TITLE
Make --version more standards compliant

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/meningotype#15]
Currently

```
meningotype/meningotype.py --version
=====================================
meningotype.py v0.8-beta
Updated 25-Mar-2017 by Jason Kwong
Dependencies: isPcr, mlst, BLAST+, BioPython
=====================================
```

First line should look like this and print to stdout:
```
meningotype 0.7b
```
You can still add the gumpf if you want, but after.

**Comment by kwongj** [comment]
Addressed in [2c16f9a](https://github.com/MDU-PHL/meningotype/commit/2c16f9ab994a74d4f79a0b6bfa695ca596bc43cf).
