### ISSUE TITLE
Installing dependencies: homebrew/science is deprecated

### ISSUE THREAD

**Issue by embatty** [MDU-PHL/meningotype#30]
homebrew/science has been deprecated. blast is now in homebrew core, ispcr and mlst are in brewsci/bio.
So I think

```
$ brew tap homebrew/science
$ brew tap tseemann/homebrew-bioinformatics-linux
```
can be changed to 

`$ brew tap brewsci/bio
`
and the installation will work.
#31

**Comment by andersgs** [comment]
Thank you for the PR.
