### ISSUE TITLE
Adding other serotype E, cnl etc

### ISSUE THREAD

**Issue by lexleong** [MDU-PHL/meningotype#32]
Hi MDU-PHL, 
I see that the users could individually update our allele database from pubmlst. But It looks like the serotyping alleles couldn't be updated. From the db directory, there is a seroALLELES.fa, which has the main serotyping but not other serotypes like MenE, MenH, CNL etc. I wonder if there is a chance to include these newly defined serogroup?
Cheers,
Lex

**Comment by andersgs** [comment]
Hi @lexleong.

We manually curate that DB. If you can help us identify suitable genomes with those serotypes, we can add them to the DB. 

Best. A.

**Comment by lexleong** [comment]
Hi @andersgs,
Great! I will search for those genomes that have the new serotypes. I will share them with you directly when I do find them.

Cheers,
Lex
