### ISSUE TITLE
Handle new Y+W serotype

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/meningotype#4]
“the  molecular basis of this dual antigenic specificity  has been determined to be due to a single amino acid  change at position 310 in the EX7E motif of the capsule  polymerase enzyme synG (also referred to as siaDY) (from
glycine to serine) or synF (siaDW-135) (from proline to serine)..

http://jcm.asm.org/content/49/1/472.full.pdf+html

**Comment by kwongj** [comment]
v0.4-beta and above now includes step to check for dual antigen specificity with W and Y using BLAST to search for 310G/310P/310S in EX7E motif.

Closed #4.
